version: 0.3.1-{build}

environment:
  matrix:
  - GENERATOR: "Visual Studio 12"
    CONFIG: Release
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON
  - GENERATOR: "Visual Studio 12"
    CONFIG: Debug
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON

  - GENERATOR: "Visual Studio 12 Win64"
    CONFIG: Release
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON
  - GENERATOR: "Visual Studio 12 Win64"
    CONFIG: Debug
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON

  - GENERATOR: "Visual Studio 14"
    CONFIG: Release
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON
  - GENERATOR: "Visual Studio 14"
    CONFIG: Debug
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON

  - GENERATOR: "Visual Studio 14 Win64"
    CONFIG: Release
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON
  - GENERATOR: "Visual Studio 14 Win64"
    CONFIG: Debug
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON

  - GENERATOR: "MinGW Makefiles"
    CONFIG: Debug
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON
  - GENERATOR: "MinGW Makefiles"
    CONFIG: Release
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON

build_script:
  - if "MinGW Makefiles"=="%GENERATOR%" set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - if "MinGW Makefiles"=="%GENERATOR%" set PATH=C:\MinGW\bin;%PATH%
  - ps: mkdir build.msvc
  - ps: cd build.msvc
  - cmake "-G%GENERATOR%" %OPTIONS% ..
  - cmake --build . --config "%CONFIG%"

test_script:
  - ctest --output-on-failure -C "%CONFIG%"
