version: 1.3.{build}

environment:
  matrix:
  - GENERATOR: "Visual Studio 12"
    CONFIG: Release
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON

  - GENERATOR: "Visual Studio 12 Win64"
    CONFIG: Release
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON

  - GENERATOR: "Visual Studio 12"
    CONFIG: Release
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON -DZF_LOG_OPTIMIZE_SIZE:bool=ON

  - GENERATOR: "Visual Studio 12 Win64"
    CONFIG: Release
    OPTIONS: -DZF_LOG_EXAMPLES:bool=ON -DZF_LOG_TESTS:bool=ON -DZF_LOG_OPTIMIZE_SIZE:bool=ON

build_script:
  - ps: mkdir build.msvc
  - ps: cd build.msvc
  - cmake "-G%GENERATOR%" %OPTIONS% ..
  - cmake --build . --config "%CONFIG%"

test_script:
  - ctest --output-on-failure -C "%CONFIG%"
